use alloc::boxed::Box;
use core::any::Any;
use core::mem::MaybeUninit;

use crate::abi::*;
#[cfg(feature = "panic-handler")]
pub use crate::panic_handler::*;
use crate::panicking::Exception;

// Per runtime instance address, stored in each exception and verified on catch,
// so a MOZ\0RUST panic from a different Rust runtime is rejected with an abort instead of being misinterpreted as ours,
// which would cause a UB.
static CANARY: u8 = 0;

#[repr(transparent)]
struct RustPanic(Box<dyn Any + Send>, DropGuard);

struct DropGuard;

// DropGuard is a zero-cost tripwire that aborts if a panic payload is destroyed outside Rust's own catch path (catch_unwind flow below),
// chiefly when foreign code catches a Rust panic and deletes(Unwind DeleteException) it instead of rethrowing,
// converting a silently swallowed panic into a loud abort.
impl Drop for DropGuard {
    fn drop(&mut self) {
        #[cfg(feature = "panic-handler")]
        {
            drop_panic();
        }
        crate::util::abort();
    }
}

#[repr(C)]
struct ExceptionWithPayload {
    exception: MaybeUninit<UnwindException>,
    // See rust/library/panic_unwind/src/gcc.rs for the canary values
    canary: *const u8,
    payload: RustPanic,
}

unsafe impl Exception for RustPanic {
    const CLASS: [u8; 8] = *b"MOZ\0RUST";

    fn wrap(this: Self) -> *mut UnwindException {
        Box::into_raw(Box::new(ExceptionWithPayload {
            exception: MaybeUninit::uninit(),
            canary: &CANARY,
            payload: this,
        })) as *mut UnwindException
    }

    unsafe fn unwrap(ex: *mut UnwindException) -> Self {
        let ex = ex as *mut ExceptionWithPayload;
        let canary = unsafe { core::ptr::addr_of!((*ex).canary).read() };
        if !core::ptr::eq(canary, &CANARY) {
            // This is a Rust exception but not generated by us.
            #[cfg(feature = "panic-handler")]
            {
                foreign_exception();
            }
            crate::util::abort();
        }
        let ex = unsafe { Box::from_raw(ex) };
        ex.payload
    }
}

pub fn begin_panic(payload: Box<dyn Any + Send>) -> UnwindReasonCode {
    // Shoudn't return back in happy path!
    crate::panicking::begin_panic(RustPanic(payload, DropGuard))
}

pub fn catch_unwind<R, F: FnOnce() -> R>(f: F) -> Result<R, Box<dyn Any + Send>> {
    #[cold]
    fn process_panic(p: Option<RustPanic>) -> Box<dyn Any + Send> {
        match p {
            // Foreign Exception
            None => {
                #[cfg(feature = "panic-handler")]
                {
                    foreign_exception();
                }
                crate::util::abort();
            }
            // Rust's Panic, forget the drop guard and return the Box.
            Some(e) => {
                #[cfg(feature = "panic-handler")]
                {
                    panic_caught();
                }
                core::mem::forget(e.1);
                e.0
            }
        }
    }
    crate::panicking::catch_unwind(f).map_err(process_panic)
}
